typedef struct cliente Cliente;
typedef struct endereco Endereco;
typedef struct rota Rota;
typedef struct produto Produto;
typedef struct devolucao Devolucao;
typedef struct pilha Pilha;
typedef struct trans Trans;

Cliente *criarListaCliente();
Rota *criarRota();
Trans *inserirCliente(Trans *transportadora);
Cliente *buscarCliente(Cliente *clientes, int id);
int vazio(Cliente *clientes);
void mostrarTodos(Trans *transportadora);
Trans *adiconarProdutos(Trans *transportadora);
void mostrarProduto(Produto *produtos);
Trans *inserirRota(Trans *transportadora, Cliente *clientes);
void mostrarRotas(Trans *transportadora);
Trans *entregarFila(Trans *transportadora);
Produto *liberarProdutos(Produto *produtos);
Trans *liberarRota(Trans *transportadora);
void mostrarUnico(Cliente *clientes);
Cliente *liberarCliente(Cliente *clientes);
Cliente *liberarClienteRota(Cliente *clientes);
Trans *inserirPilha(Trans *Transpotadora);
Pilha *criarPilha();
void mostrarPilha(Trans *Transpotadora);
Trans *CriarTrans();
Trans *entregarPilha(Trans *transportadora);
Trans *entregarPilha(Trans *transportadora);
Trans *libararPilha(Trans *transportadora);
Trans *inserirDevolucao(Trans *transportadora);
Trans *entregarDevolucao(Trans *transportadora);
void scoreDaTransportadora(Trans *transportadora);
void mostrarDevolucao(Trans *scoreDaTransportadora);